#http://rosalind.info/problems/subs/

#s = given DNA string and t = subset to find
s = 'GTGCGCGCCTAGGTGCCTAGGTCAGGCCTAGGCTTTGCCTAGGTGGCCTAGGCGGCCTAGGCCAGCCTAGGCCATGGCGCCTAGGAGCCTAGGCTGCCTAGGCTGAGAGCCTAGGACGCGGCCTAGGTCGAGTTATTGCCTAGGGTGCCTAGGTAGATAAAGCCTAGGGCCTAGGCTCGGCCTAGGCCTACGCCTAGGGTAGGCCTAGGCTGCCTAGGCTAGCCTAGGGCCTAGGTACTGCCTAGGATTACTTCTGCCTAGGTCGCCTAGGCCGCCTAGGAGCCTAGGATGGGTCGTCGGCCTAGGAGGCCTAGGGAACGGCCTAGGCAAAGACAGCCTAGGGCCTAGGACATCAATAAGCCTAGGCGGCCTAGGCGCCTAGGACAGATGCCTAGGCGCCTAGGGCCTAGGAGCCTAGGGTCGCCTAGGCTCCAGCCTAGGGGCCTAGGGCCTAGGGCCTAGGGCCTAGGGGCGCCTAGGGCTTCGCCTAGGACGCCTAGGGAGCCTAGGCGCCTAGGGGCCTAGGAGGCCTAGGGCCTAGGCATGGCCTAGGGCCTAGGGCCTAGGCCGCCTAGGGGGCCTAGGTGCCTAGGGCGCCTAGGCAAGCCTAGGGCCTAGGACCTACGCCTAGGTGCCTAGGGCCTAGGGGCCTAGGCCAAGCCTAGGACTTGCCTAGGTCGCCTAGGTGGCCTAGGTCTGCCTAGGTACCAAGCCTAGGGCCTAGGGCCTAGGGTGCCTAGGAGCCTAGGATGGCCTAGGACGCCTAGGCATTATGCCTAGGTCAGCCTAGGGCCTAGGACTCAACAGCCTAGGTGTCGCCTAGGAAAGGTTGCCTAGGTGCCTAGGTAGAGCCTAGGTTTGCCTAGGGCCTAGGGAACAGGCCTAGGAGTGTATCCTAACTGCCTAGG'
t = 'GCCTAGGGC'

indexes = []
index = -1

# Loop while true.
while True:
    # Advance location by 1.
    index = s.find(t, index+1)
    
    # Break if not found.
    if index == -1: 
        break
    else:
        print index+1,
